from __future__ import annotations

from typing import Dict

from copado_hx.api import BaseApiClient


class CrtClient(BaseApiClient):
    def __init__(self, base_url: str, pak: str, org_id: str, project_id: str):
        base = base_url.rstrip("/")
        self._pak = pak
        self._org_id = org_id
        self._project_id = project_id
        super().__init__(base, timeout=120)

    def _headers(self) -> Dict[str, str]:
        h = super()._headers()
        h["X-Authorization"] = self._pak
        return h

    def list_jobs(self) -> list[dict]:
        return self.get(f"/pace/v4/projects/{self._project_id}/jobs") or []

    def list_jobs_detailed(self) -> list[dict]:
        data = self.list_jobs()
        if isinstance(data, dict):
            items = data.get("data", data.get("items", data.get("jobs", [])))
            return items
        return data if isinstance(data, list) else []

    def trigger_build(self, job_id: str) -> dict:
        return self.post(f"/pace/v4/projects/{self._project_id}/jobs/{job_id}/builds", json={})

    def get_build_status(self, job_id: str, build_id: str) -> dict:
        return self.get(f"/pace/v4/projects/{self._project_id}/jobs/{job_id}/builds/{build_id}")

    def get_build_results(self, job_id: str, build_id: str) -> dict:
        return self.get(f"/pace/v4/projects/{self._project_id}/jobs/{job_id}/builds/{build_id}/results")

    def get_build_results_formatted(self, job_id: str, build_id: str, fmt: str = "pdf") -> bytes:
        if fmt == "pdf":
            data = self.get_build_results(job_id, build_id)
            text = self._format_as_report(data, build_id)
            return text.encode("utf-8")
        return self.get(f"/pace/v4/projects/{self._project_id}/jobs/{job_id}/builds/{build_id}/results")

    @staticmethod
    def _format_as_report(data: dict, build_id: str) -> str:
        lines = [
            "=" * 60,
            f"  CRT Test Results — Build: {build_id}",
            "=" * 60,
            "",
        ]
        status = data.get("status", data.get("buildStatus", "Unknown"))
        lines.append(f"  Status:      {status}")
        duration = data.get("duration", data.get("executionTime", ""))
        if duration:
            lines.append(f"  Duration:    {duration}")
        total = data.get("total", data.get("totalTests", 0))
        passed = data.get("passed", data.get("passedTests", 0))
        failed = data.get("failed", data.get("failedTests", 0))
        if total:
            lines.append(f"  Total:       {total}")
            lines.append(f"  Passed:      {passed}")
            lines.append(f"  Failed:      {failed}")
        lines.append("")
        tests = data.get("tests", data.get("results", data.get("testResults", [])))
        if tests:
            lines.append("-" * 60)
            lines.append("  Individual Test Results")
            lines.append("-" * 60)
            for t in tests:
                name = t.get("name", t.get("testName", "unknown"))
                tstatus = t.get("status", t.get("result", ""))
                symbol = "✓" if tstatus in ("Passed", "Succeeded") else "✗"
                duration_ms = t.get("duration", t.get("executionTime", ""))
                dur = f" ({duration_ms}ms)" if duration_ms else ""
                lines.append(f"  {symbol} {name}{dur}")
        lines.append("")
        lines.append("=" * 60)
        lines.append("  Generated by copado-hx — Copado Headless CLI")
        lines.append("=" * 60)
        return "\n".join(lines)
